#version 460

#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_scalar_block_layout : enable

#include "Common/Stages.h"
#define SHADER_STAGE COMPUTE_STAGE
#pragma shader_stage(compute)

#include "Common/Common.h"
#include "Common/Common.glsl"

#include "Compute/ThreadGroupTiling.glsl"

layout(constant_id = 0) const uint LOCAL_SIZE_X = 8;
layout(constant_id = 1) const uint LOCAL_SIZE_Y = 8;
layout(constant_id = 2) const uint LOCAL_SIZE_Z = 1;

layout(
    local_size_x_id = 0,
    local_size_y_id = 1,
    local_size_z_id = 2) in;

// Global
layout(set = 0, binding = 2, r11f_g11f_b10f) uniform readonly image2D image;
    
// Frame
layout(set = 1, binding = 0, scalar) uniform frameUBO{ Frame frame; };
layout(set = 1, binding = 1, rgba8) uniform writeonly image2D renderTarget;

// Drawcall
layout(push_constant) uniform PushConstants{
    float minValue;
    float maxValue;
};

void main()
{
    const uvec2 id = TiledGlobalInvocationID.xy;

    const uvec2 size = imageSize(image);
    
    if (id.x >= size.x || id.y >= size.y)
    {
        return;
    }

    const ivec2 storeOffset = ivec2((imageSize(renderTarget) - size) / 2);

    const vec3 inputData = imageLoad(image, ivec2(id)).rgb;

    const vec3 outputData = RemapToUnit(inputData, minValue, maxValue);

    imageStore(renderTarget, ivec2(id) + storeOffset, vec4(outputData, 1.0));
}
