#version 460

#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_scalar_block_layout : enable

#include "Common/Stages.h"
#define SHADER_STAGE COMPUTE_STAGE
#pragma shader_stage(compute)

#include "Common/Common.h"
#include "Common/Common.glsl"

#include "Compute/ThreadGroupTiling.glsl"

#define RAY_MARCH_STEP_COUNT 256

layout(constant_id = 0) const uint LOCAL_SIZE_X = 8;
layout(constant_id = 1) const uint LOCAL_SIZE_Y = 8;
layout(constant_id = 2) const uint LOCAL_SIZE_Z = 1;

layout(
    local_size_x_id = 0,
    local_size_y_id = 1,
    local_size_z_id = 2) in;

// Global
layout(set = 0, binding = 0) uniform lightUBO{ Light lights[MAX_LIGHT_COUNT]; };
layout(set = 0, binding = 1) uniform rawSamplesUBO{ vec4 rawSamples[RAW_SAMPLE_COUNT / 2]; };
layout(set = 0, binding = 2) uniform sampler2D transmittanceLut;

layout(set = 0, binding = 3, rgba32f) uniform writeonly image2D multiScatteringLut;

// Frame
layout(set = 1, binding = 0, scalar) uniform frameUBO{ Frame frame; };

#define ATMOSPHERE frame.atmo
#include "Common/Atmosphere.glsl"

vec3 RandUnitSphere(vec2 uv)
{
    const float z = 1.0 - 2.0 * uv.x;
    const float r = sqrt(max(0.0, 1.0 - z * z));
    const float phi = 2.0 * PI * uv.y;
    return vec3(r * cos(phi), r * sin(phi), z);
}

void IntegrateMedium(
    vec3 worldOrigin, vec3 worldDir, float sunTheta, vec3 sunL,
    out vec3 innerL2, out vec3 innerF)
{
    const float u = dot(worldDir, sunL);

    float endT = 0;
    const bool groundIntersection = FindClosestIntersectionWithSphere(worldOrigin, worldDir, ATMOSPHERE.planetRadius, endT);
    if (!groundIntersection)
    {
        FindClosestIntersectionWithSphere(worldOrigin, worldDir, ATMOSPHERE.atmosphereRadius, endT);
    }

    const float dt = endT / RAY_MARCH_STEP_COUNT;
    const float halfDt = 0.5 * dt;
    float t = halfDt;

    vec3 sumSigmaT = vec3(0.0);

    vec3 sumL2 = vec3(0.0);
    vec3 sumF = vec3(0.0);

    for(uint i = 0; i < RAY_MARCH_STEP_COUNT; ++i)
    {
        const vec3 worldPos = worldOrigin + t * worldDir;
        const float h = length(worldPos) - ATMOSPHERE.planetRadius;

        vec3 sigmaS, sigmaT;
        GetSigmaST(h, sigmaS, sigmaT);

        const vec3 deltaSumSigmaT = dt * sigmaT;
        const vec3 transmittance = exp(-sumSigmaT - 0.5 * deltaSumSigmaT);

        if(!HasIntersectionWithSphere(worldPos, sunL, ATMOSPHERE.planetRadius))
        {
            const vec3 rho = EvaluatePhaseFunction(h, u);

            const vec2 uv = GetTransmittanceUV(h, sunTheta);
            const vec3 sunTransmittance = textureLod(transmittanceLut, uv, 0).rgb;

            sumL2 += dt * transmittance * sunTransmittance * sigmaS * rho;
        }

        sumF      += dt * transmittance * sigmaS;
        sumSigmaT += deltaSumSigmaT;
        
        t += dt;
    }

    if(groundIntersection)
    {
        const vec3 transmittance = exp(-sumSigmaT);
        
        const vec2 uv = GetTransmittanceUV(0, sunTheta);
        const vec3 sunTransmittance = textureLod(transmittanceLut, uv, 0).rgb;

        sumL2 += transmittance * sunTransmittance * max(0, sunL.y) * (ATMOSPHERE.terrainAlbedo / PI);
    }

    innerL2 = sumL2;
    innerF  = sumF;
}

vec3 ComputeMS(float h, float sunTheta)
{
    const vec3 worldOrigin = vec3(0.0, ATMOSPHERE.planetRadius + h, 0.0);
    const vec3 sunL = vec3(cos(sunTheta), sin(sunTheta), 0.0);

    vec3 sumL2 = vec3(0.0);
    vec3 sumF = vec3(0.0);

    vec3 innerL2, innerF;
    
    for (uint i = 0; i < RAW_SAMPLE_COUNT / 2; ++i)
    {
        const vec4 rawSample = rawSamples[i];

        IntegrateMedium(worldOrigin, RandUnitSphere(rawSample.xy), sunTheta, sunL, innerL2, innerF);

        sumL2 += innerL2;
        sumF  += innerF;

        IntegrateMedium(worldOrigin, RandUnitSphere(rawSample.zw), sunTheta, sunL, innerL2, innerF);

        sumL2 += innerL2;
        sumF  += innerF;
    }

    const vec3 l2 = sumL2 / RAW_SAMPLE_COUNT;
    const vec3 f  = sumF  / RAW_SAMPLE_COUNT;

    return l2 / (1 - f);
}

void main()
{
    const uvec2 id = TiledGlobalInvocationID.xy;

    const uvec2 size = imageSize(multiScatteringLut);
    
    if(id.x >= size.x || id.y >= size.y)
    {
        return;
    }

    const vec2 uv = (id + 0.5) / size;

    const float sinSunTheta = mix(-1.0, 1.0, uv.y);
    const float cosSunTheta = sqrt(1.0 - sinSunTheta * sinSunTheta);

    const float sunTheta = asin(sinSunTheta);

    const float h = mix(0.0, ATMOSPHERE.atmosphereRadius - ATMOSPHERE.planetRadius, uv.x);

    imageStore(multiScatteringLut, ivec2(id), vec4(ComputeMS(h, sunTheta), 0.0));
}
