#version 460

#extension GL_GOOGLE_include_directive : require

#include "Common/Stages.h"
#define SHADER_STAGE COMPUTE_STAGE
#pragma shader_stage(compute)

#include "Common/Common.h"
#include "Common/Common.glsl"

#include "Compute/ThreadGroupTiling.glsl"

layout(constant_id = 0) const uint LOCAL_SIZE_X = 8;
layout(constant_id = 1) const uint LOCAL_SIZE_Y = 8;
layout(constant_id = 2) const uint LOCAL_SIZE_Z = 1;

layout(
    local_size_x_id = 0,
    local_size_y_id = 1,
    local_size_z_id = 2) in;

// Global
layout(set = 0, binding = 0) uniform lightUBO{ Light lights[MAX_LIGHT_COUNT]; };
layout(set = 0, binding = 1) uniform rawSamplesUBO{ vec2 rawSamples[RAW_SAMPLE_COUNT]; };
layout(set = 0, binding = 2) uniform sampler2D transmittanceLut;

layout(set = 0, binding = 3, rgba32f) uniform writeonly image2D multiScatteringLut;

// Frame
layout(set = 1, binding = 0) uniform frameUBO{ Frame frame; };

vec3 RandUnitSphere(vec2 uv)
{
    const float z = 1.0 - 2.0 * uv.x;
    const float r = sqrt(max(0.0, 1.0 - z * z));
    const float phi = 2.0 * PI * uv.y;
    return vec3(r * cos(phi), r * sin(phi), z);
}

vec3 EvaluatePhaseFunction(float h, float u)
{
    vec3 sRayleigh = frame.atmo.rayleightScattering * exp(-h / frame.atmo.rayleightDensityHeight);
    float sMie = frame.atmo.mieScattering * exp(-h / frame.atmo.mieDensityHeight);
    vec3 s = sRayleigh + sMie;

    float g = frame.atmo.mieScatteringAsymmetry;
    float g2 = g * g;
    float u2 = u * u;
    float pRayleigh = 3.0 / (16.0 * PI) * (1.0 + u2);

    float m = 1.0 + g2 - 2.0 * g * u;
    float pMie = 3.0 / (8.0 * PI) * (1.0 - g2) * (1.0 + u2) / ((2.0 + g2) * m * sqrt(m));

    vec3 result;
    result.x = s.x > 0.0 ? (pRayleigh * sRayleigh.x + pMie * sMie) / s.x : 0.0;
    result.y = s.y > 0.0 ? (pRayleigh * sRayleigh.y + pMie * sMie) / s.y : 0.0;
    result.z = s.z > 0.0 ? (pRayleigh * sRayleigh.z + pMie * sMie) / s.z : 0.0;

    return result;
}

// TODO move to Atmosphere.glsl
void GetSigmaST(float h, out vec3 sigmaS, out vec3 sigmaT)
{
    const vec3 rayleigh = frame.atmo.rayleightScattering * exp(-h / frame.atmo.rayleightDensityHeight);

    const float mieDensity = exp(-h / frame.atmo.mieDensityHeight);

    const float mieS = frame.atmo.mieScattering * mieDensity;
    const float mieT = (frame.atmo.mieScattering + frame.atmo.mieAbsorption) * mieDensity;

    const float ozoneDensity = max(0.0, 1.0 - 0.5 * abs(h - frame.atmo.ozoneCenterHeight) / frame.atmo.ozoneThickness);
    const vec3 ozone = frame.atmo.ozoneAbsorption * ozoneDensity;

    sigmaS = rayleigh + mieS;
    sigmaT = rayleigh + mieT + ozone;
}

// TODO STEEL-2 move to Atmosphere.glsl
vec2 GetTransmittanceUV(float h, float theta) // TODO STEEL-1 sinTheta
{
    const float u = h / (frame.atmo.atmosphereRadius - frame.atmo.planetRadius);
    const float v = 0.5 + 0.5 * sin(theta);
    return vec2(u, v);
}

void IntegrateMedium(
    vec3 worldOrigin, vec3 worldDirection, float sunTheta, vec3 sunDirection,
    out vec3 innerL2, out vec3 innerF)
{
    const float u = dot(worldDirection, sunDirection);

    const float sunIntensity = frame.sunLightIndex >= 0 ? lights[frame.sunLightIndex].intensity : 0.0f;

    float endT = 0;
    const bool groundIntersection = FindClosestIntersectionWithSphere(worldOrigin, worldDirection, frame.atmo.planetRadius, endT);
    if (!groundIntersection)
    {
        FindClosestIntersectionWithSphere(worldOrigin, worldDirection, frame.atmo.atmosphereRadius, endT);
    }

    const float dt = endT / RAY_MARCH_STEP_COUNT;
    const float halfDt = 0.5 * dt;
    float t = 0.0;

    vec3 sumSigmaT = vec3(0.0);

    vec3 sumL2 = vec3(0.0);
    vec3 sumF = vec3(0.0);

    for(uint i = 0; i < RAY_MARCH_STEP_COUNT; ++i)
    {
        const float midT = t + halfDt;
        t += dt;

        const vec3 worldPos = worldOrigin + midT * worldDirection;
        const float h = length(worldPos) - frame.atmo.planetRadius;

        vec3 sigmaS, sigmaT;
        GetSigmaST(h, sigmaS, sigmaT);

        const vec3 deltaSumSigmaT = dt * sigmaT;
        const vec3 transmittance = exp(-sumSigmaT - 0.5 * deltaSumSigmaT);

        if(!HasIntersectionWithSphere(worldPos, sunDirection, frame.atmo.planetRadius))
        {
            const vec3 rho = EvaluatePhaseFunction(h, u);
            const vec2 uv = GetTransmittanceUV(h, sunTheta);

            const vec3 sunTransmittance = textureLod(transmittanceLut, uv, 0).rgb;

            sumL2 += dt * transmittance * sunTransmittance * sigmaS * rho * sunIntensity;
        }

        sumF      += dt * transmittance * sigmaS;
        sumSigmaT += deltaSumSigmaT;
    }

    if(groundIntersection)
    {
        const vec3 transmittance = exp(-sumSigmaT);
        
        const vec2 uv = GetTransmittanceUV(0, sunTheta);
        const vec3 sunTransmittance = textureLod(transmittanceLut, uv, 0).rgb;

        sumL2 += transmittance * sunTransmittance * max(0, sunDirection.y) * sunIntensity * (frame.atmo.terrainAlbedo / PI);
    }

    innerL2 = sumL2;
    innerF  = sumF;
}

vec3 ComputeMultiScattering(float h, float sunTheta)
{
    const vec3 worldOrigin = vec3(0.0, frame.atmo.planetRadius + h, 0.0);
    const vec3 sunDirection = vec3(cos(sunTheta), sin(sunTheta), 0.0);

    vec3 sumL2 = vec3(0.0);
    vec3 sumF = vec3(0.0);

    for (uint i = 0; i < RAW_SAMPLE_COUNT; ++i)
    {
        const vec2 rawSample = rawSamples[i];

        const vec3 worldDirection = RandUnitSphere(rawSample);

        vec3 innerL2, innerF;
        IntegrateMedium(worldOrigin, worldDirection, sunTheta, sunDirection, innerL2, innerF);

        // phase function is canceled by pdf

        sumL2 += innerL2;
        sumF  += innerF;
    }

    const vec3 l2 = sumL2 / RAW_SAMPLE_COUNT;
    const vec3 f  = sumF  / RAW_SAMPLE_COUNT;

    return l2 / (1 - f);
}

void main()
{
    const uvec2 id = TiledGlobalInvocationID.xy;

    const uvec2 size = imageSize(multiScatteringLut);
    
    if(id.x >= size.x || id.y >= size.y)
    {
        return;
    }

    const vec2 uv = (id + 0.5) / size;

    const float sinSunTheta = mix(-1.0, 1.0, uv.y);
    const float cosSunTheta = sqrt(1.0 - sinSunTheta * sinSunTheta);

    const float sunTheta = asin(sinSunTheta);

    const float h = mix(0.0, frame.atmo.atmosphereRadius - frame.atmo.planetRadius, uv.x);

    imageStore(multiScatteringLut, ivec2(id), vec4(ComputeMultiScattering(h, sunTheta), 0.0));
}
